### ISSUE TITLE
Duplicate file check not applied when uploading unpacked files?

### ISSUE THREAD

**Issue by danielplohmann** [malpedia/feedback#11]
**Describe the bug**
when uploading samples as unpacked, the check whether the file's hash is already in malpedia seems to be bypassed.

**Expected behavior**
upload should be denied.

**Comment by r0ny123** [comment]
Found one too for `4c22eb33aa1d10511eaf8d13098e2687e44eaebc5af8112473e28acedac34bea` (already [there](https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_079)).
