### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by steffenenders** [malpedia/feedback#21]
**Is your feature request related to a problem? Please describe.**
Add a dark mode to the website. The dark mode should be optional and/or be triggered automatically by user settings.

**Comment by Still34** [comment]
I wrote a Stylus CSS for personal use, perhaps someone could throw together a toggle button or settings for it on the site.

https://gist.github.com/Still34/b75f2ba9eb94394e7e53c748d3594686

**Comment by steffenenders** [comment]
Malpedia now has a dark mode :)
