### ISSUE TITLE
Provide a Malpedia Library RSS/Atom Feed

### ISSUE THREAD

**Issue by 0xThiebaut** [malpedia/feedback#29]
**Is your feature request related to a problem? Please describe.**
It's hard nowadays to find good malware information feeds which aren't cluttered by less relevant entries (e.g.: company blogs have posts also covering sales, development, ...). Some commercial products even exist to filter these public feeds by training your personal ML model.

**Describe the solution you'd like**
As the Malpedia library is a high-quality curated list of entries, an RSS and/or Atom feed of new entries would be greatly appreciated in addition of the already provided Bib-File.

**Describe alternatives you've considered**
I have considered coding this myself as the API provides the required endpoints (Bib-File at `/api/get/bib`) and converting the Bib-File into an RSS/Atom feed would be trivial. Nonetheless, if this feature would be provided by Malpedia, more people could benefit from it while the feed's entries could even be of better quality (e.g.: feed entries could be tagged with the malware family which is currently not included in the Bib-File).

**Additional context**
As an example, the following Bib-File could produce the beneath Atom entry.
```bib
@online{thiebaut:20210426:anatomy:0ade0a5,
   author = {Maxime Thiebaut},
   title = {{Anatomy of Cobalt Strike’s DLL Stager}},
   date = {2021-04-26},
   organization = {nviso},
   url = {https://blog.nviso.eu/2021/04/26/anatomy-of-cobalt-strike-dll-stagers/},
   language = {English},
   urldate = {2021-04-29}
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
	<title>Malpedia Library</title>
	<link href="https://malpedia.caad.fkie.fraunhofer.de/feed/" rel="self" />
	<link href="https://malpedia.caad.fkie.fraunhofer.de/" />
	<id>https://malpedia.caad.fkie.fraunhofer.de/</id>
	<updated>2021-03-08T17:30:02Z</updated>
	<entry>
		<title>Anatomy of Cobalt Strike’s DLL Stager</title>
		<link href="https://blog.nviso.eu/2021/04/26/anatomy-of-cobalt-strike-dll-stagers/" />
		<id>https://blog.nviso.eu/2021/04/26/anatomy-of-cobalt-strike-dll-stagers/</id>
		<updated>2021-04-26T18:30:02Z</updated>
		<author>
			<name>Maxime Thiebaut</name>
		</author>
	</entry>
</feed>
```
I have furthermore searched for references to an existing Malpedia Library RSS/Atom feed in the library's HTML head but was unable to find any traces. Guessing paths (`/feed`, `.rss` and `.atom`) didn't yield any results neither.

**Comment by wagner-certat** [comment]
> Describe alternatives you've considered

One could also use the git repository and diff between pulls

**Comment by 0xThiebaut** [comment]
> 
> 
> > Describe alternatives you've considered
> 
> One could also use the git repository and diff between pulls

I am not aware of a Git repository, I assume this one is part of the private Malpedia content?

**Comment by wagner-certat** [comment]
> > > Describe alternatives you've considered
> > 
> > 
> > One could also use the git repository and diff between pulls
> 
> I am not aware of a Git repository, I assume this one is part of the private Malpedia content?

See https://malpedia.caad.fkie.fraunhofer.de/usage/faq *Is there a way to access the whole data at once?* and https://malpedia.caad.fkie.fraunhofer.de/settings *Deploy Key for Malpedia Repositories* (the sections don't have anchors, so I can't link them directly)

**Comment by 0xThiebaut** [comment]
> 
> 
> > > > Describe alternatives you've considered
> > > 
> > > 
> > > One could also use the git repository and diff between pulls
> > 
> > 
> > I am not aware of a Git repository, I assume this one is part of the private Malpedia content?
> 
> See https://malpedia.caad.fkie.fraunhofer.de/usage/faq _Is there a way to access the whole data at once?_ and https://malpedia.caad.fkie.fraunhofer.de/settings _Deploy Key for Malpedia Repositories_ (the sections don't have anchors, so I can't link them directly)

Thanks for the links, sadly these are likely part of the private Malpedia content. Accessing the pages you linked require an account which sadly is invite-only:

> Please note that Malpedia does not feature open registration. It is operated as an invite-only trust group.

Hence the feature request to at least publish the public data as an RSS/Atom feed.

**Comment by danielplohmann** [comment]
Hey all!
An Atom/RSS has been on our internal list for a long time already, we are/were just pretty swamped over the last couple months. 
 
It looks like we will be able to have more time to work on modernization of the platform in the coming weeks.
I guess the feed will be one of the first things we will be able to add as it's indeed pretty easy to implement based on how the library is organized internally.

**Comment by 0xThiebaut** [comment]
> 
> 
> Hey all!
> An Atom/RSS has been on our internal list for a long time already, we are/were just pretty swamped over the last couple months.
> 
> It looks like we will be able to have more time to work on modernization of the platform in the coming weeks.
> I guess the feed will be one of the first things we will be able to add as it's indeed pretty easy to implement based on how the library is organized internally.

Thanks! Please let me know if you need a hand to contribute on that feature; I can always provide a PR if the code-base is provided.
