### ISSUE TITLE
Pin References via Wayback Machine

### ISSUE THREAD

**Issue by danielplohmann** [malpedia/feedback#32]
**Is your feature request related to a problem? Please describe.**
It frequently happens that library entries / references are moved or deleted. 
This leads to dead links, which no one likes.

**Describe the solution you'd like**
A good way to mitigate this issue would be to push all references towards wayback machine in order to pin them for eternity.

thx to @yt0ng for the reminder. :)

**Comment by dspruell-rs** [comment]
+1 Important issue. :)

**Comment by steffenenders** [comment]
Implemented and Deployed :)
