### ISSUE TITLE
Unable to clone the malpediaclient repository mentioned in the api usage

### ISSUE THREAD

**Issue by mmulich** [malpedia/feedback#47]
**Describe the bug**
I was unable to clone the `malpediaclient` repository mentioned in https://malpedia.caad.fkie.fraunhofer.de/usage/api. Note, I was able to connect to git via ssh and clone the `malpedia` repository.

**To Reproduce**

```
$ git clone git@malpedia.caad.fkie.fraunhofer.de:malpedia/malpediaclient.git
Cloning into 'malpediaclient'...
Gitea: Unauthorized
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Successful connectivity with ssh:
```
ssh -T git@malpedia.caad.fkie.fraunhofer.de                            
Hi there! You've successfully authenticated with the deploy key named Deploy-Key for '...snipped...' (Malpedia-Site), but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
```

**Expected behavior**
I expected to be able to clone the repo.

**Suggested resolution**
Issue #4 makes the `malpediaclient` repo available on github. Perhaps the [api usage](https://malpedia.caad.fkie.fraunhofer.de/usage/api) page could be updated to use the github url. Thanks!

**Comment by danielplohmann** [comment]
Hi! 

Thanks for the notification!
We have moved the malpediaclient repository to this Github account where also the issue tracker is located. 
You can find it here: [malpediaclient](https://github.com/malpedia/malpediaclient).
I'll keep the issue open as a reminder for us to fix the information on the website so others in a similar situation will be able to find it immediately.
