### ISSUE TITLE
Unable to tag Scattered Spider in new proposal

### ISSUE THREAD

**Issue by D3fD3c0y** [malpedia/feedback#55]
**Describe the bug**
Impossible to tag the group scattered spider in new proposal.

**Expected behavior**
having an option for Scattedred SPider

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser Chrome
 - Version 119.0.6045.160

**Additional context**

**Comment by danielplohmann** [comment]
hey, thx for the pointer! the actor was added via MISP a while ago so I'm closing this as fixed.
