### ISSUE TITLE
Download Malware Families 

### ISSUE THREAD

**Issue by Dextera0007** [malpedia/feedback#62]
I'd like to download all the malware families using APIkey (https://malpedia.caad.fkie.fraunhofer.de/families) . Do you have to be a group member to obtain API key. Any work around?

**Comment by danielplohmann** [comment]
As stated in the other comment, you can use https://malpedia.caad.fkie.fraunhofer.de/api/get/families without an API token. If you want to download the actual reference samples for the malware families, you need an account.
There's no workaround for that. :)
Here's the procedure:

> Please send an email to contact@malpedia.io and reference this conversation. Note that there is a vetting procedure, so please use a short but expressive self description for increasing your chances for receiving vouches after sign-up on the website. If you have an official institutional email address (university, company, gov), sending from it helps as well (only for verification, not needed for sign up) - in any case include in the email the email address with which you want to sign up.

**Comment by Dextera0007** [comment]
Hello Daniel,

Greatly appreciate the follow-up . At this juncture I simply need the meta data  for families : names,  description, report and MD5s.

Regards,
Fritz
________________________________
De : Daniel Plohmann ***@***.***>
Envoyé : vendredi 19 avril 2024 03:06
À : malpedia/feedback ***@***.***>
Cc : Dextera0007 ***@***.***>; Author ***@***.***>
Objet : Re: [malpedia/feedback] Download Malware Families (Issue #62)


As stated in the other comment, you can use https://malpedia.caad.fkie.fraunhofer.de/api/get/families without an API token. If you want to download the actual reference samples for the malware families, you need an account.
There's no workaround for that. :)
Here's the procedure:

Please send an email to ***@***.******@***.***> and reference this conversation. Note that there is a vetting procedure, so please use a short but expressive self description for increasing your chances for receiving vouches after sign-up on the website. If you have an official institutional email address (university, company, gov), sending from it helps as well (only for verification, not needed for sign up) - in any case include in the email the email address with which you want to sign up.
