### ISSUE TITLE
Requesting API endpoint for the changlog

### ISSUE THREAD

**Issue by mmulich** [malpedia/feedback#69]
**Is your feature request related to a problem? Please describe.**

I'm looking to only update my local data based on your changelog. I'm running into HTTP 429 Too Many Requests when looking for changes.  

**Describe the solution you'd like**

You already have [the changelog exposed in html](https://malpedia.caad.fkie.fraunhofer.de/changelog). So I'm guessing the data for this is fairly accessible. I'm asking that you expose the changelog entries via a JSON API endpoint. Then I can be a good internet API citizen and only request what I need.

**Describe alternatives you've considered**

For the time being, I'll scrape the changelog html page. But that's not ideal.

---

Let me know if I can be of assistance in making this change a reality.

**Comment by steffenenders** [comment]
Instead of using the changelog itself to detect updates, have you thought of using the following API call to check for changes?:
https://malpedia.caad.fkie.fraunhofer.de/api/get/version

**Comment by mmulich** [comment]
Good suggestion, but I don't think it will work for me. Let me be more specific...

I'm only using the API for actor information. AFAIK actor info isn't present in the repository checkout. So my hope was to utilize the changes to know what actors have been created or updated.

Though, now that I look at the API again, it appears that `/api/get/actors` will work well enough. The only thing that is missing are the families that would be acquired via `/api/get/actor/<actor_id>`. I can live with this because the actor references are in the family data within your repository.

However, even with using `/api/get/actors` I still run into issues with HTTP 429 Too Many Requests when trying to get the actor bibliography info at `/api/get/bib/actor/<actor_id>`.

Thoughts?

**Comment by mmulich** [comment]
Ok, I've got what I need between using `/api/get/actors` and delaying requests after HTTP 429 has been reached. Thanks for thinking about the problem with me.
